cache: bundler
cache: yarn
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
language: ruby
script:
  - RAILS_ENV=test bundle exec rake all:test
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
