dist: bionic
sudo: false

cache: bundler
cache: yarn

cache:
  directories:
    - vendor/bundle
    - $HOME/.yarn/bin

language: ruby
rvm:
  - 2.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RAILS_ENV=test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - bundle exec rake all:test
